Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
a=np.array([3,4,5,6])
b=np.array([1,2,3,5])
filter=a>b #greater than a and b

In [2]:
print(filter)

[ True  True  True  True]


In [3]:
filter=a<b #lesser than b
print(filter)

[False False False False]


In [4]:
filter=(a==b) #equal t
print(filter)

[False False False False]


In [5]:
filter=(a>=b)
filter

array([ True,  True,  True,  True])

In [6]:
filter=(a<=b)
filter

array([False, False, False, False])

In [7]:
a=np.array([1,1,4,5])
b=np.array([1,1,3,2])
filter=(a==b)
filter

array([ True,  True, False, False])

Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array


In [8]:
a=np.array([[1,2,3],[3,4,5],[6,5,7]]).reshape(3,3)

In [9]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 5, 7]])

In [10]:
b=np.sum(a)

In [11]:
b

36

In [12]:
np.sum(a,axis=0) #Column wise

array([10, 11, 15])

In [13]:
np.sum(a,axis=1) #Row wise

array([ 6, 12, 18])

Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [14]:
np.add(15,16)

31

In [15]:
np.subtract(36,15)

21

In [16]:
np.multiply(3,2)

6

In [17]:
int(np.divide(36,4))

9

Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree

In [18]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [19]:
import pandas as pd
import random 

In [32]:
a={"Marks":pd.Series([498,499,497],index=["Steve","Ariavdam","Don"]),"Rank":pd.Series([1,2,3],index=["Steve","Ariavdam","Don"])}

In [34]:
a

{'Marks': Steve       498
 Ariavdam    499
 Don         497
 dtype: int64,
 'Rank': Steve       1
 Ariavdam    2
 Don         3
 dtype: int64}

In [35]:
s=pd.DataFrame(a)

In [36]:
s

Marks  Rank
Steve       498     1
Ariavdam    499     2
Don         497     3

Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [43]:
s.iloc[0]

Marks    498
Rank       1
Name: Steve, dtype: int64

In [45]:
list(s.index)

['Steve', 'Ariavdam', 'Don']

In [49]:
s.keys()

Index(['Marks', 'Rank'], dtype='object')

Write a Pandas program to join the two given dataframes along rows and assign all data.

In [58]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                         'key2': ['K0', 'K1', 'K0', 'K1'],
                         'A': ['A0', 'A1', 'A2', 'A3'],
                         'B': ['B0', 'B1', 'B2', 'B3']})
   

In [59]:
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [61]:
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                          'key2': ['K0', 'K0', 'K0', 'K0'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})
    


In [62]:
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [71]:
result=pd.merge(left,right,how="left")

In [72]:
result

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [74]:
import numpy as np
import pandas as pd

In [86]:
a={"Test 1":pd.Series([np.NaN,np.NaN,100]),"Test 2":pd.Series([200,np.NaN,100],)}

In [87]:
a

{'Test 1': 0      NaN
 1      NaN
 2    100.0
 dtype: float64,
 'Test 2': 0    200.0
 1      NaN
 2    100.0
 dtype: float64}

In [88]:
a=pd.DataFrame(a)

In [90]:
a.isna()

Test 1  Test 2
0    True   False
1    True    True
2   False   False

Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [93]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64
